### ISSUE TITLE
Manifest for copied assets

### ISSUE THREAD

**Issue by liqueflies** [webpack-contrib/copy-webpack-plugin#105] opened 2016-12-21 10:10 UTC
Hi,
what about manifest for hash copied assets?
There are some plugins that work with copy-webpack?

Thank you.

**Comment by pinkstrings** [comment] 2016-12-29 21:09
I found a hacky way around this using the `transform` option and the `md5-file` module:

```javascript
new CopyWebpackPlugin([
  {
    from: 'foo.zip',
    to: 'foo-[hash].zip',
    transform: function(content, filepath) {
      var manifestContents = {'foo.zip': 'foo-' + require('md5-file').sync(filepath) + '.zip'}
      require('fs').writeFileSync('manifest.json', JSON.stringify(manifestContents))
      return content
    }
  }
])
```

**Comment by imerr** [comment] 2017-02-01 19:41
I'm running into the same issue here trying to use laravel mix (which is a wrapper around webpack to simplify common things)
They use webpack-stats-plugin to write out a manifest file
Which seems to do something like this https://github.com/FormidableLabs/webpack-stats-plugin/issues/3 :
```js
    function() {
      this.plugin('done', function(stats) {
        require('fs').writeFileSync(
          './dist/manifest.json',
          JSON.stringify(stats.toJson().assetsByChunkName));
      });
    }
```

I can't for the live of me figure out what the critera for files to show up in stats is
Could someone more familiar with webpack maybe give me some pointers?

**Comment by SebastianS90** [comment] 2017-02-19 12:31
If you know the hash length, then you can use `StatsWriterPlugin` and extract hashes from the `stats.asset.name` field as presented in https://github.com/kevlened/copy-webpack-plugin/issues/104#issuecomment-280915911

**Comment by davidmpaz** [comment] 2017-06-20 16:49
@SebastianS90 how can I make it work with directories. Let say I am copying like this:
```
config.plugins.push(new CopyWebpackPlugin([
    {
        from: resourcesPath + '/images',
        to: outputPath
    }
]));
```

Curently I dont see a way to overcome with this. 

It would be very nice if this is added to this plugin.

**Comment by SebastianS90** [comment] 2017-06-24 07:33
@davidmpaz I also don't see an easy way to get a manifest for a mapping from source file to output file.
You can have a look at the [example stats object](https://raw.githubusercontent.com/webpack/analyse/master/app/pages/upload/example.json) and there you see the `assets` property. It does not contain the source of each asset.

What my solution does is to take the output file path, remove the hash and create a mapping from the unhashed to the hashed output file path. For my use-case, I reference files via their unhashed output file and use the created manifest to find the hashed output file.

If you want to have a manifest for copied files from their original source to the created asset, then you probably need to extend this plugin.

**Comment by davidmpaz** [comment] 2017-06-25 09:34
Hi @SebastianS90 thanks for the hints. Actually I don't think the plugin it is too far from there. I have been looking into code and found some places where functionality could be hooked, based on some configuration option: `nameTemplate` or something for example. My problem for making a pull request is my lack of webpack knowledge. Maybe you could help out with some answers?

* [In this line](https://github.com/kevlened/copy-webpack-plugin/blob/master/src/writeFile.js#L84) the file is added to assets.
    - Is this the proper way to make webpack process assets, so the file is then treated the same as it is with loaders or from an import?
    - Is this a good place for applying the naming scheme ([name]-[hash].[ext])? Taking into account webpack configuration regarding base path and else, ofcourse.

* [This other line](https://github.com/kevlened/copy-webpack-plugin/blob/master/src/index.js#L61) as far as I see from tests keep track of all files written with hashes included also.
    - When calling callback to finish `emit`, could this be a better place to modify webpack with processed files?

I have given small read to [some plugins](https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js) dealing with writing manifest files, but can not extract much that I could apply here due to lack of knowledge.

Thanks in advance.

**Comment by SebastianS90** [comment] 2017-06-25 10:07
@davidmpaz

**First question:**
The way to store assets is more or less the right way. Usually you would use a `Source` object from [`webpack-sources`](https://github.com/webpack/webpack-sources), but this plugin fits the [required interface](https://github.com/webpack/webpack-sources/blob/master/lib/Source.js) for `compilation.assets`.
I think that this is the right place to do the renaming (i.e. replace variables like `[ext]` and `[hash]`. As you see, the actual logic is done in `loader-utils`. But I'm not a webpack expert, so there might be a better solution for this. On the other hand, I don't think you need to touch that part. Just use the `file.webpackTo` value for the manifest.


**Second question:**
That variable is written [here](https://github.com/kevlened/copy-webpack-plugin/blob/v4.0.1/src/writeFile.js#L73-L75). It only stores the hash, not the complete output path of each file. As far as I can see it is used to prevent outputting the same file again and again, when webpack does incremental builds.

You could do:
* Add a `manifest` variable to [`globalRef`](https://github.com/kevlened/copy-webpack-plugin/blob/v4.0.1/src/index.js#L56). It should be declared outside the `emit`phase such that it is preserved on incremental builds. Keys will be the original path, values the computed output path.
* You can populate the manifest right before [this line](https://github.com/kevlened/copy-webpack-plugin/blob/v4.0.1/src/writeFile.js#L83) with `file.absoluteFrom` and `file.webpackTo` (maybe there is something better than `absoluteFrom`)
* You can stringify and save the manifest as an asset after [this Promise](https://github.com/kevlened/copy-webpack-plugin/blob/v4.0.1/src/index.js#L77-L84).
* Remember to make it configurable

**Hint for the future:**
If you link to specific lines in GitHub please do not select a branch. Instead, select a specific commit ref or the latest tag. This ensures that the links are stable. Otherwise the links aren't useful in the future, because added/removed lines change the line numbers in the file and your link will point to something else.

**Comment by davidmpaz** [comment] 2017-06-27 08:13
Hi @SebastianS90 ,

many thanks for all the hints :+1: . Just as a follow up. I have gone through the code again and I think we are closer as we though. I hope that from discussion danethurber/webpack-manifest-plugin#45 we will be able to get a valuable outcome to find a solution for this issue.

Reason is that the assets are already included in Webpack compilation by this plugin. There is no need to make the plugin responsible for writing such manifest if we have other plugins doing that job already.

I think that what we are missing is communication. Maybe @kevlened could provide helpful output for this in both threads?

cheers

**Comment by michael-ciniawsky** [comment] 2017-10-05 19:40
Duplicate of #104

**Closed by michael-ciniawsky** 2017-10-05 19:40 UTC

**Comment by airtonix** [comment] 2018-03-14 00:25
@michael-ciniawsky not really, #104 is about not using hashes in production. Where as this is simply that copied assets do not show up in webpack-manifest.

**Comment by strarsis** [comment] 2021-02-13 17:32
Has `manifest` support be added now to `copy-webpack-plugin` now?
The [`copy-globs-webpack-plugin`](https://github.com/qwp6t/copy-globs-webpack-plugin) is similar and has `manifest` support built in.

**Comment by alexander-akait** [comment] 2021-02-13 17:42
No need assets manifest plugin can extract original path use `asset.info.sourceFilename`

**Comment by strarsis** [comment] 2021-02-13 17:43
@alexander-akait: Awesome! One problem less.
