### ISSUE TITLE
copy files to different directory in windows

### ISSUE THREAD

**Issue by sk29110** [webpack-contrib/copy-webpack-plugin#283] opened 2018-08-27 21:07 UTC
I want to find out if you have resolved the issue of coping files to different directory in windows? It seems to stop at 95% with my envrionment  webpack@3.10.0

**Comment by evilebottnawi** [comment] 2018-08-28 09:18
@sk29110 please create minimum reproducible test repo?

**Comment by sk29110** [comment] 2018-08-28 16:17
I though this is just matter of yes/no. I just want to copy files from current directory to another directory using drive letter like "k:\myserver" in windows10

`
var environment = {
    aos_www_script_path: "k:/myserver",
    aos_resource_path: "k:/myserver"
};

module.exports = {
    watch: true, 
    entry: { 
        "WorkCalendarPage": ["./src/pages/my-new-page"]
    },
    output: {
        path: __dirname,
        filename: "./dist/my[name].js"
    },
    resolve: { 
        extensions: ['', '.min.js', '.js', '.ts']
    },   
    devtool: 'source-map',    
    plugins: [          
        new CopyWebpackPlugin([{ from: "dist/", to: environment.aos_www_script_path }])        
    ],
    module: {
        loaders: [
          { test: /\.ts$/, loaders: ['ts-loader'], exclude: /node_modules/ },
          { test: /\.css$/, loader: 'style-loader!css-loader' },          
          { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
          { test: /\.(woff|woff2)$/, loader: "url?prefix=font/&limit=5000" },
          { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
          { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" },
          { test: /\.ts$/,loader: 'tslint-loader',enforce: "pre" }
        ]
    }
}`

I am using symbolic link to get around for now.

**Comment by evilebottnawi** [comment] 2018-08-28 16:27
@sk29110 please create minimum reproducible test repo, not put here config

**Comment by evilebottnawi** [comment] 2018-08-28 16:28
Also glob doesn't works with difference drivers, i.e. you can copy files from `C:` to `K:`

**Comment by evilebottnawi** [comment] 2018-11-08 09:32
For copying files to server, better use deployer tool, doesn't use this plugin, because some plugins can use `afterEmit` event (this plugins use `emit` event) and it is out of scope

**Closed by evilebottnawi** 2018-11-08 09:32 UTC
Labels: flag: Needs more info
