### ISSUE TITLE
Transfer copy-webpack-plugin to @webpack-contrib

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/copy-webpack-plugin#135] opened 2017-07-04 14:43 UTC
@kevlened - Quick introduction. I'm Josh, I run @webpack-contrib ( Webpacks loader & plugin ecosystem ). copy-webpack-plugin is still heavily downloaded and at least from appearances, it looks like you could use some help with the maintenance.

The process is simple enough assuming the above is true and depending on if / or how much you want to be involved going forward shouldn't take more then 15 minutes, 1 commit & a transfer.

For some libs we transfer in, the previous authors just wanted to hand it off. Others maintain along with the contrib org-maintainers it's really up to you as far as what maintenance arrangements we make.

If you are interested, you can ping me here or DM me on Twitter and we can work out the particulars.

**Comment by cletusw** [comment] 2017-09-27 19:38
@d3viant0ne @kevlened Was there any progress on this? Thanks.

**Comment by cletusw** [comment] 2017-09-27 19:39
Also, dupe of #131 ?

**Comment by d3viant0ne** [comment] 2017-09-27 22:52
Dupe, no. I'm the person to talk to in regards to webpack-contrib

**Closed** 2017-09-29 14:54 UTC
