### ISSUE TITLE
v6.0.0 requires node >= 10.17

### ISSUE THREAD

**Issue by angelikatyborska** [webpack-contrib/copy-webpack-plugin#490] opened 2020-05-18 07:05 UTC
### Expected Behavior

According to this project's Changelog and the `engine` attribute in `package.json` (https://github.com/webpack-contrib/copy-webpack-plugin/blob/6f34c86057c6e9897856f3249b7c9fa105b4ad57/package.json#L16), v6.0.0 should work with Node >= 10.13.

### Actual Behavior

When I try to update from `5.1.1` to `6.0.0`, I cannot even install `6.0.0` because it requires a new version of `move-file` that requires Node >= 10.17 and my project is on Node 10.15.3.

```
$ node -v
v10.15.3

$ git diff
diff --git a/assets/package.json b/assets/package.json
index b462f56f1..4414aa13e 100644
--- a/assets/package.json
+++ b/assets/package.json
@@ -26,7 +26,7 @@
     "chart.js": "^2.9",
     "clipboard": "^2.0",
     "cookies-js": "^1.2.3",
-    "copy-webpack-plugin": "^5.1.1",
+    "copy-webpack-plugin": "^6.0.0",
     "css-loader": "~3.5.3",
     "draft-js": "^0.11",
     "draft-js-export-html": "~1.4.1",

$ yarn install
yarn install v1.15.2
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error move-file@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.17". Got "10.15.3"
error Found incompatible module
```

**Comment by evilebottnawi** [comment] 2020-05-18 10:45
Duplicate of https://github.com/npm/cacache/issues/37

Wordaround - update node@10 to latest version

**Closed by evilebottnawi** 2020-05-18 10:45 UTC
