### ISSUE TITLE
Copied file is empty

### ISSUE THREAD

**Issue by PierBover** [webpack-contrib/copy-webpack-plugin#28] opened 2016-03-01 02:02 UTC
I'm trying to copy the output file of Webpack into another folder and I'm getting this random error where sometimes the copied file is empty.

![image](https://cloud.githubusercontent.com/assets/226483/13415165/4fede930-df1e-11e5-886e-cbe15e686993.png)

The original file is not empty.

![image](https://cloud.githubusercontent.com/assets/226483/13415179/672246c8-df1e-11e5-9f53-cfad59e1b76d.png)

I'm doing this to copy the file:

```
            new CopyWebpackPlugin([
                  {
                        from: "./build/build.js",
                        to: "../../FRONT/js/build.js"
                  }
            ])
```

It's the first time I'm using Webpack...

Could this be a bug or am I doing something wrong?

**Comment by jmlopez-rod** [comment] 2016-03-15 04:43
@PierBover, this sounds like the problem I posted: https://github.com/kevlened/copy-webpack-plugin/issues/15, see the comments for a solution or just add the changes from my pull request: https://github.com/kevlened/copy-webpack-plugin/pull/21/files

**Comment by mo-lon** [comment] 2016-04-13 15:35
Its intermittently happening for me. @jmlopez-rod I tried your solution but it did not work for me.

**Comment by PierBover** [comment] 2016-04-13 15:50
I ended up using Gulp for copying stuff and other duties

**Comment by kevlened** [comment] 2016-04-15 05:43
This is happening because the file you're trying to copy (the webpack bundle) isn't completely built yet. The ability to copy files after everything has been built isn't currently supported, but it's a nice feature

**Comment by guzgarcia** [comment] 2016-10-22 18:52
Is still not implemented this functionality?

**Comment by kevlened** [comment] 2016-10-23 20:01
@guzgarcia It isn't, and there's no timeline for when it will. The plugin isn't currently designed to copy files after webpack is finished. Doing that would actually require writing directly to the filesystem (while we only write to webpack's compilation.assets, and let webpack ultimately write to the filesystem).

Perhaps it just makes sense for another plugin (or tool, like grunt or gulp) to copy after a build. However, I'm open to ideas if this can be easily shimmed in.

**Comment by jmlopez-rod** [comment] 2016-10-24 16:32
@kevlened , that's what my PR was supposed to do. It is probably outdated, but the main thing was this:

```
if (compilation.assets[inProduction]) {
 +        compilation.assets[relFileDest] = compilation.assets[inProduction];
 +      } else if (stat.mtime.getTime() > lastGlobalUpdate) {
 +        compilation.assets[relFileDest] = {
 +          size: function() {
 +            return stat.size;
 +          },
 +          source: function() {
 +            return fs.readFileSync(absFileSrc);
 +          }
 +        };
 +      }
```

First we check if the file we are trying to copy is help by webpack. If it is then we just make a copy to another asset with the name of your copy. That way webpack will output the copy when it is time to emit. If it is not in the webpack domain then we just create another asset for webpack the way you originally did.

**Comment by michael-ciniawsky** [comment] 2017-10-05 22:19
Duplicate of #15

**Closed by michael-ciniawsky** 2017-10-05 22:19 UTC
