### ISSUE TITLE
Chaining another loader?

### ISSUE THREAD

**Issue by stephan-v** [webpack-contrib/copy-webpack-plugin#121] opened 2017-04-06 13:47 UTC
Is there a way to chain a loader when copying over files?

Let's say I want to copy over some SVG files, is it possible to directly apply something like `svgo-loader` to them while they are being copied over to a new directory?

Thanks for reading, cheers.

**Comment by GabrielGil** [comment] 2017-06-19 16:58
I am also on the same situation. Wanted to process a JS file first and then copy the result. Is it possible?

**Comment by cletusw** [comment] 2017-09-27 19:40
@stephan-v Not entirely clear on the use case, but wouldn't you just use [file-loader](https://github.com/webpack-contrib/file-loader) for this?

**Comment by cletusw** [comment] 2017-09-27 19:42
Dupe of #98 ?

**Comment by stephan-v** [comment] 2017-09-28 08:15
Does the file-loader 'kick in' when the files are being copied over though? I guess it is similar to #98

**Comment by cletusw** [comment] 2017-09-28 15:28
Yeah, I was kinda thinking file-loader *instead of* this plugin, but I guess that doesn't always work.

**Comment by michael-ciniawsky** [comment] 2017-10-05 21:38
Duplicate of #98

**Closed by michael-ciniawsky** 2017-10-05 21:38 UTC
