### ISSUE TITLE
[Feature] node_modules copy detection and monorepo (lerna) support

### ISSUE THREAD

**Issue by admosity** [webpack-contrib/copy-webpack-plugin#210] opened 2018-01-26 18:05 UTC
We have a shared assets library shared between multiple frontends under a single monorepo and would like to be able automatically detect if node_modules is used in the path to allow the copy to search recursively upwards. Due to the hoisting nature of packages to the top level of the monorepo, this breaks node_modules relative copy paths.

**Comment by evilebottnawi** [comment] 2018-01-29 09:40
@admosity can you describe more verbosely you use case? Example repo will be great!

**Comment by admosity** [comment] 2018-01-29 22:58
### Use case

We have multiple frontends that rely on a shared assets repository that is distributed via npm packaging. These frontends have to be developed together. Using lerna with hoist, the packages get moved to the monorepo level and the copy configuration that originally relied on the relative path would break.

### Reproduction monorepo created at:
https://github.com/admosity/lerna-copy-webpack-plugin-reproduce

There's two angular-cli frontends in there that leverage the webpack copy plugin under the hood. Both repos have a git dependency (https://github.com/admosity/shared-assets-lib): 
```json
    "shared-assets-lib": "admosity/shared-assets-lib#master"
```

Which holds the following cat image:
![image](https://user-images.githubusercontent.com/4655972/35538817-26ee9b5c-051d-11e8-97ff-45eb00a750d3.png)

The frontends have a single page that just shows the cat `packages/client1/src/app/app.component.html` which has:
```html
<img src="/cat-assets/cat.jpg" alt="">
```

The copy configuration has this entry in both the frontends:
```json
        {
          "glob": "**/*",
          "input": "../node_modules/shared-assets-lib/assets",
          "output": "./cat-assets/"
        }
```

When going to each individual project, you are able to

**Comment by evilebottnawi** [comment] 2018-01-30 09:53
@admosity Thank you, this is very rare use case. Therefore, hardly anyone is implementing it except you, so PR welcome. Seems it is more bug then feature.

**Comment by smirnowld** [comment] 2018-11-30 12:49
+1, would also be useful for projects using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/)

**Comment by evilebottnawi** [comment] 2018-11-30 12:55
PR welcome

**Comment by evilebottnawi** [comment] 2019-02-19 16:56
@smirnowld can't reproduce with latest lerna, both examples work fine

**Comment by IanVS** [comment] 2020-01-22 20:39
What is the recommended way to copy files from `node_modules`?  When using yarn workspaces, there's no guarantee whether it will be in the project's node_modules or hoisted up to the root level.

**Comment by evilebottnawi** [comment] 2020-01-23 09:35
@IanVS Can you create minimum reproducible test repo with examples, i think yarn have ENV variable where stored path to the node_modules directory

**Comment by fox2081** [comment] 2020-11-06 02:31
```
new CopyWebpackPlugin([{
    from: `${path.dirname(require.resolve(`${moduleName}/package.json`))}/xxx`,
    to: 'xxx',
  }
]),
```

When work with `yarn workspace`, I use `path.dirname` and `require.resolve` to resolve module's real path.

**Closed** 2021-03-22 16:17 UTC
Labels: flag: Needs more info

**Comment by aruniverse** [comment] 2021-06-16 16:46
would this work with pnpm workspaces?

**Comment by alexander-akait** [comment] 2021-06-16 16:48
@aruniverse yes, please use `require.resolve`
