### ISSUE TITLE
"Options should be array" error - constructor only takes array args. 

### ISSUE THREAD

**Issue by takuy** [webpack-contrib/copy-webpack-plugin#455] opened 2020-04-29 22:01 UTC
- Operating System: Windows 10
- Node Version: 6.14.4
- NPM Version: 14.0.0
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 5.1.1

### Expected Behavior

It would be expected the documented syntax for the plugin works.

### Actual Behavior

If the constructor is structured like the documentation, you get an error like this:

```
CopyPlugin Invalid Options

options should be array

ValidationError: CopyPlugin Invalid Options
    at validateOptions (C:\Users\user\code\app\node_modules\copy-webpack-plugin\node_modules\schema-utils\src\validateOptions.js:32:11)
```
### Code

Error-causing code:
```js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  plugins: [
    new CopyPlugin({
      patterns: [
        { from: 'source', to: 'dest' },
        { from: 'other', to: 'public' },
      ],
    }),
  ],
};
```
Good code:
```js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  plugins: [
        new CopyPlugin(
            [
                { from: 'source', to: 'dest' },
                { from: 'other', to: 'public' },
            ]
        ),
  ],
};
```

### How Do We Reproduce?

Create webpack config with documented syntax.

**Comment by jonathanRinciari** [comment] 2020-04-29 23:30
Oh man this just tripped me up for the last hour or so. I was about to downgrade to try and get around this. Thanks!

**Comment by calebTomlinson** [comment] 2020-04-30 03:58
I can confirm I am having this problem as well.

I see from the git history that you just made a breaking change that hasn't been released yet, but it's frustrating and time consuming that I'm working with a freshly installed module and reading the [official docs](https://webpack.js.org/plugins/copy-webpack-plugin/), but it doesn't work as documented.

Perhaps release branches would reduce these issues.

**Comment by evilebottnawi** [comment] 2020-04-30 09:08
We have a next branch in master because we prepare next release, please use documentation from here https://github.com/webpack-contrib/copy-webpack-plugin/tree/v5.1.1, release will be soon

**Comment by jonknowles** [comment] 2020-04-30 16:17
I don't know why this issue was closed - I searched the open issues because of this problem an hour ago, but only found this solution now. The issue is not resolved until the incorrect public documentation has been fixed. Until then, people are going to be trying to understand why this is not working and looking through your open issues and not finding this.

**Comment by jonathanRinciari** [comment] 2020-04-30 16:37
This should absolutely not be closed.. This is clearly an issue and this ticket serves as a point of reference for people who have this problem. This should be closed once the change has been merged..

**Comment by maddog986** [comment] 2020-05-01 21:47
I think the OP had the wrong version, but it is happening on for me on version 5.1.1. I just spent way to much time with this problem.

**Comment by takuy** [comment] 2020-05-01 23:34
> I think the OP had the wrong version, but it is happening on for me on version 5.1.1. I just spent way to much time with this problem.

Sorry. That was a typo on my part.

**Comment by Hypnosphi** [comment] 2020-05-04 17:50
@evilebottnawi do you think you can mark `5.1.1` branch as default in GitHub for now, to prevent this kind of confusion?

**Comment by rodvlopes** [comment] 2020-05-05 14:07
Short answer:
```js
    new CopyWebpackPlugin([
      { from: 'source', to: 'dest' },
    ])
```

Long answer:

> ...please use documentation from here https://github.com/webpack-contrib/copy-webpack-plugin/tree/v5.1.1, release will be soon

**Comment by marco-a** [comment] 2020-05-05 21:26
I'm having the same issue. Please fix.

**Comment by xuya227939** [comment] 2020-05-08 03:25
It's too much！！！,copy-webpack-plugin ```5.1.1``` is
```
new CopyPlugin([
    { from: '...', to: '...' },
])
```

README.md is
```
new CopyPlugin([
    { from: './src/assets/js', to: '../src/assets/js/' },
])
```

**Comment by katheryn-k** [comment] 2020-05-10 21:05
Same problem =(

**Comment by lychees** [comment] 2020-05-12 05:32
Same here.

**Comment by chenka** [comment] 2020-05-15 08:33
Same here, doc is confuse.

**Comment by evilebottnawi** [comment] 2020-05-15 16:55
6 version was released https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.0.0

**Closed by evilebottnawi** 2020-05-15 16:55 UTC

**Comment by m1stermanager** [comment] 2020-07-17 01:59
https://webpack.js.org/plugins/copy-webpack-plugin/ is still showing the old syntax. gave up and googled. here I am. weird issue to have?
