### ISSUE TITLE
(BROKEN ON MACOS) Binary files lose executable permissions after copy.

### ISSUE THREAD

**Issue by NxRoot** [webpack-contrib/copy-webpack-plugin#771] opened 2024-03-24 16:56 UTC
Binary file execution is completely broken.

This is my code:
```tsx
new CopyWebpackPlugin({
    patterns: [
      {
        from: path.resolve(__dirname, 'src/main/_py'),
        to: path.resolve(__dirname, '.webpack/main/_py'),
      }
    ]
 })
```
This will throw an EACCES error every time we try to execute binary files.

<img height="40px" src="https://iili.io/JhvEYmu.png"/>

The files get copied to the desired folder, however they **lose all the permissions to be executed** via `spawn` or `exec` or any other method to execute them.

I know it is a **issue from your plugin** because Ive added a delay before executing the files and quickly copied the files manually before they get executed, this way it works but obviously we cant even package the app this way.

I recommend you take a look at [this plugin](https://github.com/GeKorm/webpack-permissions-plugin) and fix your own plugin.
Thanks

**Comment by alexander-akait** [comment] 2024-03-25 11:35
Duplicate of https://github.com/webpack-contrib/copy-webpack-plugin/issues/35, feel free to send a PR, what we need -

If an asset has `stats` in its assets info, we will apply some stats before write them, we need send a PR to webpack and send PR here to write them (under the option)

**Closed by alexander-akait** 2024-03-25 11:35 UTC

**Comment by NxRoot** [comment] 2024-03-25 13:13
> Duplicate of #35, feel free to send a PR, what we need -
> 
> If an asset has `stats` in its assets info, we will apply some stats before write them, we need send a PR to webpack and send PR here to write them (under the option)

Don't understand what you are saying, it should be an easy fix.
A simple `chmod` after copying the files would do it...
```tsx
var file = "PATH/TO/FILE"

// Get current permissions
var stats = fs.statSync(file)
var currentPermission = '0' + (stats.mode & parseInt('777', 8)).toString(8);

// Set permissions on copied files
fs.chmodSync(file, currentPermission)
```

**Comment by alexander-akait** [comment] 2024-03-25 13:14
We can't just run `fs.chmodSync`, here, because writting assets is a part of webpack logic, not a plugin

**Comment by NxRoot** [comment] 2024-03-25 13:21
> We can't just run `fs.chmodSync` here, because writting assets is a part of webpack logic, not a plugin

Well, the [webpack-permissions-plugin](https://github.com/GeKorm/webpack-permissions-plugin) is doing a `chmodSync` as part of plugin code, how come your `copy-webpack-plugin` is not able to do it since it is meant to copy files?

I can only understand that from a perspective where you dont want to automatically set permissions, thats ok, but...

Is there any chance of adding a new property to the `patterns` so that the developer can specify permissions to be applied to the copied files?

**Comment by alexander-akait** [comment] 2024-03-25 14:50
Because this plugin is buggy, it uses Node.js `fs`, but in real usage webpack uses not only Node.js fs, it is possible to use memfs and any other custom fs, this plugin will work for some cases, but it is an invalid solution
