### ISSUE TITLE
Conflict with clean-webpack-plugin?

### ISSUE THREAD

**Issue by kevinzheng** [webpack-contrib/copy-webpack-plugin#261] opened 2018-05-19 01:01 UTC
When I use `clean-webpack-plugin` with `copy-webpack-plugin`, I got `ERROR in [copy-webpack-plugin] unable to locate 'dist/manage.bundle.js' at '/Users/XXX/Workspace/project/dist/manage.bundle.js'`, but when I remove `clean-webpack-plugin`, it works fine, what the problem is?

```javascript
    plugins: [
        new CleanWebpackPlugin(['dist']),
        new UglifyJSPlugin({
            sourceMap: true
        }),
        new CopyWebpackPlugin([
            {
                from: 'dist/manage.bundle.js',
                to: '../public/js/'
            }
        ], { debug: 'info' })
    ],
```

**Comment by evilebottnawi** [comment] 2018-05-19 14:17
@kevinzheng because `CleanWebpackPlugin` remove `dist/manage.bundle.js`, it is expected

**Comment by evilebottnawi** [comment] 2018-05-21 10:00
@kevinzheng i don't understand your, you remove files and when want to copy this file?

**Comment by kevinzheng** [comment] 2018-05-25 16:06
@evilebottnawi , I want to `clean-webpack-plugin` before the compiling, and `copy-webpack-plugin` after the compiling, ehh... I want to clean the `dist` dir before building, and  copy the building result to another dir.

**Comment by evilebottnawi** [comment] 2018-05-25 16:10
@kevinzheng out of scope `copy-webpack-plugin`, use any `copy` plugin to move something after build process.

**Comment by cfkxzsat** [comment] 2018-11-04 01:47
same here..

**Comment by mycoin** [comment] 2019-05-08 03:34
``` javascript
new CleanWebpackPlugin({
        cleanStaleWebpackAssets: false, // resolve conflict with `CopyWebpackPlugin`
}),
```

**Comment by evilebottnawi** [comment] 2019-05-08 09:56
Somebody can create reproducible test repo?

**Comment by chrisblossom** [comment] 2019-10-24 22:27
The issue is `copy-webpack-plugin` does not persist the assets copied in webpack's current asset list. I attempted to resolve this issue in #360 but the PR looks to be stale. If a maintainer can provide some insight on how to move that PR forward I would be willing to make the necessary changes to solve this.

**Comment by evilebottnawi** [comment] 2019-10-25 10:40
@chrisblossom this PR is breaking change, we will fix it in next release

**Comment by tobia** [comment] 2019-11-11 18:07
`cleanStaleWebpackAssets: false` does not solve the problem for me.

I use CopyWebpackPlugin to copy static files into the bulid folder:

```
  plugins: [
    new CleanWebpackPlugin(),
    new MiniCssExtractPlugin({
      filename: '[name].[hash].css',
    }),
    new WebpackMd5Hash(),
    new CopyPlugin([
      { from: 'public', to: '.' }
    ]),
  ],
```

If I use `webpack --watch`, everything seems to work on the first build. But from the second bulid onward, the static assets are removed by CleanWebpackPlugin (which is correct, because they might have been modified) but they are not copied again by CopyWebpackPlugin.

**Comment by JohnnyFun** [comment] 2019-12-07 07:23
In my case, I was using `cleanAfterEveryBuildPatterns` instead of `cleanOnceBeforeBuildPatterns`. When I changed it to clean _before_, it cleans prior to the copy plugin running.

**Comment by Trolldemorted** [comment] 2020-03-30 15:09
@evilebottnawi can you estimated when a release with a fix will be available?

**Comment by pankerit** [comment] 2020-04-06 17:47
same problem

**Comment by evilebottnawi** [comment] 2020-04-07 08:55
Hope current month

**Closed** 2020-04-27 16:19 UTC
Labels: semver: Major, severity: 3 (broken), type: Bug
