### ISSUE TITLE
copy file permissions

### ISSUE THREAD

**Issue by TheDirigible** [webpack-contrib/copy-webpack-plugin#733] opened 2023-03-07 23:28 UTC
### Feature Use Case

I'm surprised this isn't the default

**Comment by alexander-akait** [comment] 2023-03-08 13:56
Duplicate of https://github.com/webpack-contrib/copy-webpack-plugin/issues/35

**Closed by alexander-akait** 2023-03-08 13:56 UTC

**Comment by alexander-akait** [comment] 2023-03-08 17:18
You can send a PR to fix it, but I think we need some extra work with our FS, I will look soon, but it is just duplicate
