### ISSUE TITLE
Build order for HtmlWebpackPlugin module?

### ISSUE THREAD

**Issue by danchristian** [webpack-contrib/copy-webpack-plugin#133] opened 2017-06-26 12:59 UTC
## Description

The `/dist` folder is in `.gitignore` so therefore empty,  the build is then failing in production as `CopyWebpackPlugin` is looking in `/dist` for files to copy elsewhere but it errors with: 

```
ERROR in [copy-webpack-plugin] unable to locate '/dist/app.html'
```

I would expect `HtmlWebpackPlugin` to build these files first before the `CopyWebpackPlugin` starts to look for them? [Asking in the HtmlWebpackPlugin repo](https://github.com/jantimon/html-webpack-plugin/issues/718#issuecomment-310715772)  and it seems to possibly point to `CopyWebpackPlugin` using `emit` instead of `after-compile`?

### Config
```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

new HtmlWebpackPlugin({
    title: 'App',
    filename: 'app.html',
    template: './src/app.pug',
    inject: 'head',
    chunks: ['app'],
    hash: true
}),

new CopyWebpackPlugin([
    {from: 'dist/app.html',   to: '../Views/Shared/_layout.cshtml'}
])
```
## Environment
```
Node.js v6.9.4
darwin 16.6.0
npm --version (3.10.10)
npm ls webpack (2.6.1)
npm ls html-webpack-plugin (2.28.0)
```

**Comment by garrensweet** [comment] 2017-08-04 19:40
@danchristian  Did you ever find a solution to this? I forked that repository and tried many, many things. I could not, however, get it to wait for the generated file to be completed before attempting the copy, however. I did try the `after-compile` tip that was suggested, to no avail.

**Comment by danchristian** [comment] 2017-08-04 19:58
@garrensweet Unfortunately not. I ended up taking the module out of our build process as it couldn't deliver what we needed.

**Comment by seotory** [comment] 2017-09-14 05:43
I'm gat same issue. 
any updates?

**Comment by michael-ciniawsky** [comment] 2017-10-05 22:42
Duplicate of #15

**Closed by michael-ciniawsky** 2017-10-05 22:42 UTC
