### ISSUE TITLE
plugin throwing when not matching (v6)

### ISSUE THREAD

**Issue by aaarichter** [webpack-contrib/copy-webpack-plugin#494] opened 2020-05-20 09:51 UTC
- Operating System:
- Node Version: 14
- NPM Version: 6
- webpack Version: 4
- copy-webpack-plugin Version: 6.0.1

I'm using the copy-webpack-plugin in a library that is used in multiple project with different structures and cases, which are handled by multiple patterns in copy-webpack-plugin. 

### Expected Behavior / Situation
The `from` v5 behavior where a not matching pattern did not throw and exits webpack

### Actual Behavior / Situation
When no files are matched, the plugin throws and exits webpack

```console
LOG from copy-webpack-plugin
<e> unable to locate 'modules/**/static/*.*' at '/project/modules/**/static/*.*'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! program@3.0.0 assets: `webpack`
npm ERR! Exit status 2
```
### Modification Proposal
- don't throw
- log warning should be yellow (not red) and should be displayed in verbose mode.

**Comment by aaarichter** [comment] 2020-05-20 10:00
I just discovered `noErrorOnMissing` pattern option 😰 . 
It doesn't work as a global option and was not needed to be set in v5 right? If that is the case, then https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/CHANGELOG.md#-breaking-changes should mention the behavior change as breaking change

**Comment by evilebottnawi** [comment] 2020-05-20 10:05
Please do not remove `Reproducible steps`, we can't help you without the configurations/reproducible steps, I am closing, feel free to update issue and I will reopen it.

Looks you have invalid `context`, because your path stats with `/` at error

**Comment by evilebottnawi** [comment] 2020-05-20 10:06
`noErrorOnMissing` is feature for `v6` for ignoring empty pattens

**Closed by evilebottnawi** 2020-05-20 10:05 UTC
