### ISSUE TITLE
Compress images with image-webpack-loader

### ISSUE THREAD

**Issue by moisesdeguia** [webpack-contrib/copy-webpack-plugin#147] opened 2017-10-02 06:57 UTC
For me this plugin can be interesting to proccess all my images and compress for production. Some way to do that with image-webpack-loader?

**Comment by michael-ciniawsky** [comment] 2017-10-05 22:04
Duplicate of #98 (Tracking Issue)

**Closed by michael-ciniawsky** 2017-10-05 22:04 UTC
